
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= janConjGrad
# Cuda source files (compiled with cudacc)
CUFILES		:= conjGradVer5.cu   cuTimer.cu
# CUDA Dependency files (e.g. kernels)
#CUDEPS		:= 2Dconvolution_kernel.cu 
# C/C++ source files (compiled with gcc / c++)
#CCFILES		:= 2Dconvolution_gold.cpp

# Additional libraries needed by the project
USECUBLAS       := 1
USEBLAS	  := 1

################################################################################
# Rules and targets

include ../../common/common.mk
